# Generated by Django 3.0.7 on 2020-06-29 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('twitter_username', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=50, null=True)),
                ('github_username', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userportfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('project_description', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Please enter the URL of your project page.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PortfolioApp.UserPortfolio')),
            ],
        ),
    ]
